version: "3.8"

services:
  nlp_sentence_similarity:
    build: .
    container_name: my_app
    volumes:
      - .:/app
    environment:
      PYTHONUNBUFFERED: 1
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      NVIDIA_VISIBLE_DEVICES: all
    #  entrypoint to keep the container running
    entrypoint: tail -f /dev/null
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 1 # Number of GPUs to use, adjust if you have more